name: Update Assets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [ master ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npx pnpm i

      - name: Update assets
        run: npx tsx follower/index.ts 

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update followers.svg"
          add: "assets/followers.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}